---
title: "Curso Auditoria de Dados - Caso Estudo Hospital"
author: "Fl?vio Brito"
date: "23/10/2016"
output:
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: tango
    fig_width: 10
    fig_height: 3
    self_contained: false
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
#Retirando um data frame da mem?ria
hospay <- NULL

#Lendo o arquivo no padr?o csv com separador ; e criando o data frame nf
hospay <- read.csv(file="./dados/Hospital.csv",stringsAsFactors = FALSE, sep=";" )
  
```

```{r}
#Estrutura do Arquivo
str(hospay)

#Resumo dos Dados
summary(hospay$Measure.start.date)
summary(hospay$Measure.End.Date)
```

```{r}
#Lista as categorias em um

levels(hospay$Measure.start.date)
levels(hospay$Measure.End.Date)

# #Checando
# hospay$Measure.start.date <- gsub("[[:blank:]]", "", hospay$Measure.start.date)
# hospay$Measure.End.Date <- gsub("[[:blank:]]", "", hospay$Measure.End.Date)

#Datas com Missing
any(is.na(as.character(hospay$Measure.start.date)))
any(is.na(as.character(hospay$Measure.End.Date)))

#Pagamentos com Missing
any(is.na(as.numeric(hospay$Payment)))



hospay$Measure.start.date <- as.Date(hospay$Measure.start.date,"%m/%d/%Y" )
hospay$Measure.End.Date <- as.Date(hospay$Measure.End.Date,"%m/%d/%Y" )

class(hospay$Measure.start.date)
class(hospay$Measure.End.Date)

str(hospay$Measure.start.date)
str(hospay$Measure.End.Date)

# Tratamento de valores em Strings
# Remover sinal de dollar e vírgula

hospay$Payment <- as.numeric(gsub("[$,]", "", hospay$Payment))
hospay$Lower.estimate <- as.numeric(gsub("[$,]", "", hospay$Lower.estimate))
hospay$Higher.estimate <-as.numeric(gsub("[$,]", "", hospay$Lower.estimate))

#Limpa os brancos 
hospay$Hospital.name < - trimws(hospay$Hospital.name)

#Qual o total de hospitais prentes na lista
length(hospay$Hospital.name)
#Quantos hospitais
length((unique(hospay$Hospital.name)))
#Quais os hostitais
unique(hospay$Hospital.name)

#Pivot
# Contagem de casos por Hospital

pv1 <-data.frame(table(hospay$City, hospay$Value.of.care.category, hospay$State))
table(hospay$City, hospay$State)

#Frequencia
pv1 <- NULL
pv1 <- with(hospay,table(hospay$State))
pv1.freq <- table(hospay$State)
pv1.prob <- prop.table(pv1.freq)
pv1.out <- cbind(pv1.freq, pv1.prob)

#Mudando o nome das colunas
colnames(pv1.out) <-c("Freq","Perc(%)") 

#Frequencia por faixa - dados numéricos
faixa1 <-cut(hospay$Payment, breaks = -100:30000,include.lowest = TRUE)
stack(table(faixa1)) #transpoe


faixa1 <-cut(hospay$Payment, seq(from = 1000, to = 40000, by = 5000),include.lowest = TRUE)
stack(table(faixa1)) #transpoe

faixa1 <-cut(hospay$Payment, seq(1000, 40000, 5000),right = FALSE)
stack(table(faixa1)) #transpoe


#include.lowest = TRUE inclui o menor
faixa2 <-cut(hospay$Payment, breaks = 10, dig.lab = 2,labels=c("A","B", "C", "D", "E", "F", "G", "H", "I", "J")) # força os labels
summary(faixa2)
stack(summary(faixa2))
faixa2 <-cut(hospay$Payment, breaks = 10, dig.lab = 2,labels=c(1:10)) # força os labels
summary(faixa2)
stack(summary(faixa2))



faixa <-cut(hospay$Payment, breaks = c(100,10000,20000, 30000), labels=c("medio", "maior", "avaliar"))
stack(table(faixa)) #transpoe

#Steam and Leaf - dados numéricos
stem(hospay$Payment, scale =.5)

#Agregação
by(data=hospay$Payment, IND=hospay$State, FUN=mean)
with(hospay, by(hospay$Payment, list(hospay$Payment.category,hospay$State), mean))
with(hospay, table(hospay$Payment.category,hospay$State))


aggregate(hospay$Payment ~ hospay$State, FUN=mean, hospay)


# Removendo hospitais que apresentam MISSING

hospay<-hospay[hosp$Payment.category !="Not Available" & hosp$Payment.category !="Number of Cases Too Small",]

summary(hospay)

hospay_pneumo <- NULL


hospay_pneumo <- subset(hospay,  hospay$State == "CA" & grepl("pneumonia",hospay$Payment.measure.name) )

# Contagem de casos por Hospital

table(hospay_pneumo$City, hospay_pneumo$Value.of.care.category)

with(hospay_pneumo,
     table(hospay_pneumo$Payment.category=="Greater than the National Average Payment",
           year(hospay_pneumo$Measure.start.date)==2012,
           months(hospay_pneumo$Measure.start.date),
           City,
           useNA = "ifany"))

#useNA = "ifany" para contar NA


My.Data[grep("^G45", My.Data$x), ]



head(hospay$Payment)

library(reshape2)
hosp_melt<-melt(data=hospay,id=c(2,5,9,11), measure=as.numeric(c(13)), value.name='Estimate') 
names(hosp_melt)



library(sqldf)
names(hosp_melt) [3] <- "PaymentMeasureName"
hosp_est <- sqldf("select State, avg(Estimate) as Estimate 
                  from hosp_melt 
                  where paymentmeasurename = 'Payment for heart attack patients' 
                  group by State")

```
